name: CI Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  # JOB 1 : Tests Unitaires
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Run Unit Tests
        #Exclure tests intégration
        run: mvn test -Dtest=!PricingIntegrationTest

  # JOB 2 : Qualité (Bonus)
  quality:
    needs: unit-tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Run Checkstyle and Spotbugs
        # SkipTests pour ne faire que l'analyse statique
        run: mvn verify -DskipTests

  # JOB 3 : Tests d'Intégration
  integration-tests:
    needs: quality # depend-on quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          
      - name: Run Integration Tests
        # Exec que les tests intégrations
        run: mvn test -Dtest=PricingIntegrationTest